### ISSUE TITLE
Build issues with Vite in the React example

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#1]
Hi, @ngxson!

First of all, thank you for creating lib. I've previously tried [rahuldshetty/llm.js](https://github.com/rahuldshetty/llm.js) and [tangledgroup/llama-cpp-wasm](https://github.com/tangledgroup/llama-cpp-wasm), which are also great bindings, but they hadn't made it as easy as running an `npm install` to get it running. So, kudos for that!

I've successfully integrated wllama into [MiniSearch](https://github.com/felladrin/MiniSearch), which is also using Vite as a bundler, and found some issues when building it: `tsc` complains about some typescript types, and `vite build` fails due to some Vite build-rules.

<details>
  <summary>Screenshots</summary>

  <img width="1102" alt="image" src="https://github.com/ngxson/wllama/assets/418083/15d6a039-baa0-46e4-895e-1687d7a95625">
  <img width="922" alt="image" src="https://github.com/ngxson/wllama/assets/418083/ec32926b-1f0e-492b-b193-c50a19169068">
</details>

You can reproduce those issues by running `npm run build` in the [examples/reactjs](https://github.com/ngxson/wllama/tree/f5eaf163b42634d06f2566cd9d0df030d4bb3d88/examples/reactjs) folder of wllama repository.

Could you kindly review the issues that are preventing the Vite/React example from running successfully?

P.S. Meanwhile, what I'm doing as a workaround is copying the prebuilt wllama files to the dist folder and and forcing Vite to skip checking them.

**Comment by ngxson** [comment]
Hi and thanks for the info. It's true that I didn't tried `npm run build`. This is definitely a bug on my side and will be a blocking point for the upcoming [retrieval example](https://github.com/ngxson/wllama/tree/retrieval) which is based on reactjs.

For the `export type` error that you got, I believe that it's already fixed in the latest build on npm, maybe you can try `npm i @wllama/llama@latest` to bump to latest version?

For the other bug of `new URL(...)`, I'm having a look. Will update to you when it's fixed.

**Comment by ngxson** [comment]
I release version 1.4.1 that fixed the bug. You can upgrade to the latest version by running `npm i @wllama/llama@latest`

Please pay attention that there's a breaking change on `CONFIG_PATHS` (added 2 more JS file to the list), you can take the code below:

```js
import wllamaSingleJS from '@wllama/wllama/src/single-thread/wllama.js?url';
import wllamaSingle from '@wllama/wllama/src/single-thread/wllama.wasm?url';
import wllamaMultiJS from '@wllama/wllama/src/multi-thread/wllama.js?url';
import wllamaMulti from '@wllama/wllama/src/multi-thread/wllama.wasm?url';
import wllamaMultiWorker from '@wllama/wllama/src/multi-thread/wllama.worker.mjs?url';

const CONFIG_PATHS = {
  'single-thread/wllama.js'       : wllamaSingleJS,
  'single-thread/wllama.wasm'     : wllamaSingle,
  'multi-thread/wllama.js'        : wllamaMultiJS,
  'multi-thread/wllama.wasm'      : wllamaMulti,
  'multi-thread/wllama.worker.mjs': wllamaMultiWorker,
};
```

**Comment by felladrin** [comment]
Thank you! With v1.4.1 the Vite/React demo is building and working flawlessly!

I've also confirmed that the snippet you shared above worked on my side!
(Except when the server has cross-origin isolation headers; but it's something to discuss in a separate issue later).

**Comment by ngxson** [comment]
The bug you mentioned about `import("./wllama.js")`. I accidentally disable security headers when I run the test, so didn't spot the bug. The line import statement now takes the correct `wllama.js` file given by `CONFIG_PATHS`, so you don't need to change anything, just need to `npm i @wllama/llama@latest`
