### ISSUE TITLE
What does `noTEE` do?

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#107]
While trying to debug an issue I noticed a new boolean setting called `noTEE`. I'm curious: what does it do exactly?

**Comment by ngxson** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Tee_(command)): In computing, tee is a command in command-line interpreters (shells) using standard streams which reads standard input and writes it to both standard output and one or more files, effectively duplicating its input.

In the context of wllama, TEE is enabled by default to copy file stream to both cache + wasm module at the same time. `noTEE` disable copying stream to wasm module.

**Comment by flatsiedatsie** [comment]
Ah, so that's what makes it download only, and not actually load the model. Got it, thanks.
