### ISSUE TITLE
Unable to import in React.js

### ISSUE THREAD

**Issue by cbh778899** [ngxson/wllama#111]
Hi, I've found this excellent library and I was trying to use it in my React.js project. I'm not using Vite and Typescript, and I installed it using `npm install @wllama/wllama`.  
  
My js code is like this:
```js
// ...
import { Wllama } from "@wllama/wllama"
// ...
```
And when I was trying to compile it, I've got the error:
```
ERROR in ./src/utils/worker.js 10:0-40
Module not found: Error: Can't resolve '@wllama/wllama' in '/path/to/src/utils'
```
  
I'm not a professional at this but it seems like the compiler is trying to import `@wllama/wllama` inside `src` instead of `node_modules`, which I never met before.  
  
Please check it to see are there any solutions, it's kind of impossible to include Vite and Typescript in my project now...

**Comment by ngxson** [comment]
For pure js, you can import `@wllama/wllama/esm/index.js` and compiled worker files from
- `@wllama/wllama/esm/multi-thread/*`
- `@wllama/wllama/esm/single-thread/*`

At worst, you can import it directly to global scope, example here: https://github.com/ngxson/wllama/blob/master/examples/basic/index.html

**Comment by cbh778899** [comment]
> For pure js, you can import `@wllama/wllama/esm/index.js` and compiled worker files from
> 
> * `@wllama/wllama/esm/multi-thread/*`
> * `@wllama/wllama/esm/single-thread/*`
> 
> At worst, you can import it directly to global scope, example here: https://github.com/ngxson/wllama/blob/master/examples/basic/index.html

Thanks for the advice , the import of index works now, however it throughs error
```
Error: Cannot find module 'http://localhost:3000/esm/single-thread/wllama.js'
    at esm|lazy|groupOptions: {}|strict namespace object:5:1
    at async ProxyToWorker.moduleInit (worker.ts:405:1)
    at async Wllama.loadModel (wllama.ts:488:1)
    at async Wllama.loadModelFromUrl (wllama.ts:421:1)
    at async loadModel (worker.js:43:1)
```
I've searched on this and it seems like it's going to import a static model, so I leave `esm/*` in public folder, and I've checked it can be accessed both directly and using `await import()`:   
  
![Screenshot from 2024-09-05 14-09-38](https://github.com/user-attachments/assets/63e49dcd-e573-4ab0-8b1f-3c487d8bc9e4)  
  
I know it's kinda strange so if there's no solution, I'll try use it globally.

**Comment by cbh778899** [comment]
I managed to use Vite+React and it works normally now, thanks for your help.

**Comment by Nithur-M** [comment]
> * @wllama/wllama/esm/multi-thread/*

Hi @ngxson,
This returns module not found error. Any fix for this?

**Comment by ngxson** [comment]
Alternative method: you should have a look at CDN section in the README:

![Screenshot 2025-01-15 at 15 50 39](https://github.com/user-attachments/assets/34e5e0ef-4c08-44b4-9d63-3ead17006bd5)

**Comment by Nithur-M** [comment]
It works! Thank you so much @ngxson
