### ISSUE TITLE
[bug]: llama_decode error when send the same prompt twice

### ISSUE THREAD

**Issue by cbh778899** [ngxson/wllama#114]
Hi, I've found that when completion using `useCache: true`, and pass the same prompt, for example `[{role: 'user', content: 'hello'}]` to the same instance one by one, at the second time it'll get error `llama_decode: failed to decode, ret = -1`.

![image](https://github.com/user-attachments/assets/292dd313-48a1-4520-9152-eb911b4f7e3f)

To be more clearly, If I ask `hi`, ask `hello` and ask `hi` again, everything is fine. But if I ask `hi`, wait the response, ask `hi` again, it'll output this error.  
  
I'm sure it is related to the `useCache` attribute but I'm wondering what is happening?

**Comment by ngxson** [comment]
Yes there should be an error in the `useCache` option. It will be fixed soon.
