### ISSUE TITLE
The current configuration of Emscripten with `PTHREAD_POOL_SIZE=32` for multi-threading may be causing memory wastage

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#16]
About this config:
https://github.com/ngxson/wllama/blob/65bbcc07c52d9105936bcd783e3e718ca93d1c5f/scripts/docker-compose.yml#L35

Some people recommend using `PTHREAD_POOL_SIZE=navigator.hardwareConcurrency`, so it won't create more workers than the number of logical processors available to run threads on the user's computer:
- https://github.com/emscripten-core/emscripten/issues/14407#issuecomment-861038985
- https://www.jackyoustra.com/blog/binary-analysis#multithreading-discovered-later-in-the-story

I believe that would already be an improvement.

---

But then I started thinking of some other option, which I don't know if it would work, but could prevent any waste of resources: to use `PTHREAD_POOL_SIZE=self.WLLAMA_PTHREAD_POOL_SIZE`.

By doing so, you could set `self.WLLAMA_PTHREAD_POOL_SIZE = nbThreads` before the `multi-thread/wllama.js` script is initialized, below line 156 here:
https://github.com/ngxson/wllama/blob/65bbcc07c52d9105936bcd783e3e718ca93d1c5f/src/wllama.ts#L155-L157

Do you think it's doable?

**Comment by ngxson** [comment]
Thanks for pointing that out. Yes, it should be doable.

It would be even better to have `PTHREAD_POOL_SIZE` to be exactly equal to `nbThreads`. I'll need to dive into the source code of emscripten to see if it's possible for not.

**Comment by flatsiedatsie** [comment]
I've also read that setting threads to half of those available works better, as the thread normally can't all be fed optimally.

See: https://github.com/tangledgroup/llama-cpp-wasm/issues/1

**Comment by ngxson** [comment]
@flatsiedatsie By default, on multi-thread build, we already take half number of available threads `(hardwareConcurrency / 2)`.

This is also true for native version of llama.cpp, not just wllama, because nowadays CPU usually have 2 threads per 1 core, but these 2 threads share the same SIMD component.
