### ISSUE TITLE
Feature request: Add an option for Verbose Mode, for opt-in console logs

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#17]
Something I liked from https://llama-cpp-wasm.tangledgroup.com/example-single-thread.html is that the `stderr` from `llama.cpp` is not printed to the console.

Could Wllama not print anything to the console, and only do it if the user sets some argument (e.g. `verbose`) during the initialization?

**Comment by ngxson** [comment]
Yes it would be useful. Ideally, user could pass a custom logger into the constructor of `class Wllama`. By default, we use `console` as logger, but passing `null` as logger will effectively disable it.
