### ISSUE TITLE
[Feature Request] Allow setting `dynatemp_range` in `SamplingConfig`

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#3]
`SamplingConfig` has already a lot of options:

![code](https://github.com/ngxson/wllama/assets/418083/a7ee1540-0688-4cbd-94f8-428b6ba1dc41)

But I missed an important one: [dynatemp_range](https://github.com/ggerganov/llama.cpp/blob/facb8b56f8fd3bb10a693bf0943ae9d69d0828ef/common/sampling.h#L32C17-L32C31), which when set with a positive number, makes use of the dynamic temperature sampler.

Would you consider adding it, along with the `dynatemp_exponent` option?

## More info [[Reference](https://github.com/ggerganov/llama.cpp/blob/facb8b56f8fd3bb10a693bf0943ae9d69d0828ef/examples/server/README.md?plain=1#L210C1-L212C70)]

`dynatemp_range`: Dynamic temperature range. The final temperature will be in the range of `[temperature - dynatemp_range; temperature + dynatemp_range]` Default: `0.0`, which is disabled.

`dynatemp_exponent`: Dynamic temperature exponent. Default: `1.0`

**Comment by ngxson** [comment]
With https://github.com/ngxson/wllama/commit/3acbfcde9e8108ec65d53c429c01ded0fcf7e11d , 4 sampling params are added:
- `penalize_nl`
- `dynatemp_range`
- `dynatemp_exponent`
- `logit_bias`

**Comment by felladrin** [comment]
Thank you for the fast response!

I see the params were added to the `samplingInit` function:

https://github.com/ngxson/wllama/blob/7330db3afc10477afdc2c946f4ecd99961ac4844/src/wllama.ts#L258-L279

But the `SamplingConfig` interface wasn't updated:

https://github.com/ngxson/wllama/blob/7330db3afc10477afdc2c946f4ecd99961ac4844/src/wllama.ts#L44-L61

In a quick look, it seems one solution would be setting the `samplingInit` config argument to be of type `SamplingConfig`:

```typescript
async samplingInit(config: SamplingConfig)
```

What do you think?

**Comment by ngxson** [comment]
Yeah you’re right. That was a bad design by me. I’ll fix that tomorrow when I come back from my trip.

**Comment by ngxson** [comment]
Thank you for reporting the issue. It should be fixed in v1.6.0:

https://github.com/ngxson/wllama/blob/4c917e6f47154bb3bb74e5ac23bde4c85c9efeab/src/wllama.ts#L263

**Comment by felladrin** [comment]
Working great now!
Thank you for the update!
