### ISSUE TITLE
Post on Reddit/r/LocalLlama?

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#53]
Wllama is currently the only project that can run larger models like Mistral 7B in browsers that do not support WebGPU out of the box yet ( Safari, Firefox).

That's quite a feat, and newsworthy? Might be fun to create a post about it on Reddit?

**Comment by ngxson** [comment]
Yes it would be nice. I heard about this reddit but I don't use social network very often, I almost forgot about this.

Btw, do you think we should make a proper chat UI example before making a post of social platforms? (I also have LinkedIn)

I already have some reactjs code laying around from [alpaca.cpp-webui](https://github.com/ngxson/alpaca.cpp-webui) so I just adapt it real quick for wllama (may take me 1 or 2 days to finish)

**Comment by flatsiedatsie** [comment]
That might be a good idea. But why people insist on using React I will never understand. IMHO it makes it so needlessly difficult to look at the actual code, and copy it. But that's up to you :-)

**Comment by ngxson** [comment]
I'd agree that from software engineer perspective, a more "structural" framework like angular would be a better choice. But the other half of my brain (the UX designer) wants a language that is easier to express the UX/UI. React turns out to be easy enough for non-tech designers to understand.

Tooling for reactjs is also easier which cuts down a lot of time (this is mostly personal preference - I still appreciate other frameworks like angular, vue, etc.)

**Comment by flatsiedatsie** [comment]
I've created a quick minimal demo for you:

https://flatsiedatsie.github.io/wllama_mistral_7b_demo/

Since your time and skills are valuable and rare, it makes more sense to spend it on developing Wllama itself, rather than created web demos?

Building demo's, on the other hand, is something within my reach, and I would be happy to do so.

**Comment by flatsiedatsie** [comment]
Feel free to add it to the readme. I'll can do a post on Reddit, sure.

> The reason is that personally I need a good UI with a manageable code structure to really test out new features. Maybe I'll focus on that in next week or the week after that.

Ah, that makes sense.

**Comment by flatsiedatsie** [comment]
I created a post on Reddit: https://www.reddit.com/r/LocalLLaMA/comments/1cy6ifz/all_web_browsers_can_now_run_larger_models/
