### ISSUE TITLE
Error when running `h2o-danube2-1.8b-chat` and `phi-2` models when `cache_type_k` is set to `q4_0` or `q8_0`

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#54]
This is the first model (which I know fits the memory) that I see failing to run.

Here's what I see on the console:

<img width="780" alt="image" src="https://github.com/ngxson/wllama/assets/418083/c2b5f091-1bcd-40a9-94b0-c1c8da1495a3">

Got this same result with all quants of those repositories:
- https://huggingface.co/Felladrin/gguf-h2o-danube2-1.8b-chat
- https://huggingface.co/bartowski/h2o-danube2-1.8b-chat-GGUF
- https://huggingface.co/Felladrin/gguf-sharded-h2o-danube2-1.8b-chat

Note: I've confirmed those models are running on the latest (compiled today) llama.cpp binary. I've also tested the sharded version. It might be some issue with Emscripten conversion.

**Comment by felladrin** [comment]
I got the same issue when using a `Phi-2` model, and after some investigation, I found the cause:
Those models are triggering these errors when `cache_type_k` is set to "q4_0" or "q8_0".
The only cache type working is `f16`.

**Comment by ngxson** [comment]
Yes this should be related to #41 . Please note that `cache_type_k` is quite experimental in llama.cpp, so sometimes we expect to get errors.
