### ISSUE TITLE
404-ed model still ended up in wllama_cache?

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#57]
Because I [made a typo](https://github.com/ngxson/wllama/issues/56) in the URL of a local model file I noticed something strange. It seems that invalid URL ended up in the `wllama_cache` anyway. 

I checked to see if my code was perhaps adding the URL to the cache manually, but didn't think so, and also didn't find that.

The result is that my projects thinks the model is loaded, but then Wllama crashes when loading it.

Perhaps it cached the 404 page?

<img width="600" alt="Screenshot 2024-05-24 at 13 08 37" src="https://github.com/ngxson/wllama/assets/805405/0504ec8e-52b0-497d-8e1d-c33bd628ae99">

(currently my code tries to recognise an event object, and see that as an indication that the (down)load process failed, and not the actual loading of the model itself. See also: https://github.com/ngxson/wllama/issues/56

**Comment by ngxson** [comment]
Resolved by #59 . Any invalid URL (which does not have status code 200) will be rejected by fetch API.
