### ISSUE TITLE
Error when loading a model via relative path

### ISSUE THREAD

**Issue by felladrin** [ngxson/wllama#63]
<img width="1006" alt="Screenshot 2024-06-05 at 00 13 20" src="https://github.com/ngxson/wllama/assets/805405/53dcda65-ada4-4b5a-af20-ced79637fb14">

_Originally posted by @flatsiedatsie in https://github.com/ngxson/wllama/issues/61#issuecomment-2148507658_

---

It seems wllama will always fail to load models via relative path due to this line:

https://github.com/ngxson/wllama/blob/041e2abfa4335b0e765d676156b5ecd1b894ff1b/src/downloader/multi-downloads.ts#L48

For example:

`new URL("/models/mermaid/Mermaid-Llama-3-3B-Pruned.04_K_M-00001-of-00008-gguf")`

<img width="530" alt="image" src="https://github.com/ngxson/wllama/assets/418083/2ef61f15-f29a-489e-824f-ab32dc8df021">

**Comment by ngxson** [comment]
Yes this is because I leave this code as-is when I copied `WebBlob` implementation from huggingface.js.

I think we can get rid of `URL` and simply use `string` here. I can assign this issue to you if you want. What do you think @felladrin ?

**Comment by felladrin** [comment]
Oh yeah, I can remove the URL, test it, and then create a pull request. You may assign it to me.

**Comment by flatsiedatsie** [comment]
Whoop! Time for a new version release? I was implementing the simpler approach this enabled today, but had forgotten that it wasn't in the release yet. Loving it though, it makes me code a lot simpler.
