### ISSUE TITLE
Would it be possible to release a new version?

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#67]
The "use the first chunk name only" feature would be very useful.

**Comment by ngxson** [comment]
Sorry I was quite busy recently. In fact, I wanted to see if I can fix the problem when loading files > 2GB in this release, but seems like it's more complicated than I thought, so let's delay it until next version.

The current main branch looks good to me now. I'll try to release it in next hours.

**Comment by flatsiedatsie** [comment]
Thanks!

> I was quite busy recently

Good!

>  the problem when loading files > 2GB

Which problem is that?

**Comment by ngxson** [comment]
It's not possible to load a single big file (need to split into small files) ==> https://github.com/ngxson/wllama/pull/52#issuecomment-2138242650

Ability to load big file can be useful when we want to pick a gguf file from local

**Comment by ngxson** [comment]
v1.11.0 released on npm

Changelog: https://github.com/ngxson/wllama/releases/tag/1.11.0

**Comment by flatsiedatsie** [comment]
Thank you
