### ISSUE TITLE
BitNet support

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#69]
I'm curious: if Llama.cpp adds BitNet support (which looks imminent), will Wllama be able to run Bitnet models too by simply upgrading the Llama.cpp version? Or will there be more things that need to happen?

https://github.com/ggerganov/llama.cpp/pull/7931

**Comment by ngxson** [comment]
It totally depends on llama.cpp side, but I suppose that it will be transparent to us (much like how support for phi-3 is added)

**Comment by flatsiedatsie** [comment]
Any second now.. GGerganov has already signed off on it.

I was thinking: could be cool to immediately create a demo showcasing BitNet in the browser via Wllama? I could create one, but so far I've not been able to compile Wllama myself. I'm trying to get that working again now though.

**Comment by flatsiedatsie** [comment]
I've managed to get compiling working (reinstalled Docker).

I then tried to use the very latest version of Llama.cpp with BitNet support. Unfortunately I ran into an error:

<img width="391" alt="Screenshot 2024-06-23 at 17 45 12" src="https://github.com/ngxson/wllama/assets/805405/66dc6af2-4abd-443e-8afc-28b8c67b74be">

and another attempt:

<img width="393" alt="Screenshot 2024-06-23 at 18 23 11" src="https://github.com/ngxson/wllama/assets/805405/ba93cebe-c8c0-4f54-87cb-bd15cc9ea416">

and

<img width="384" alt="Screenshot 2024-06-23 at 17 45 55" src="https://github.com/ngxson/wllama/assets/805405/47dd3387-0e51-4fdd-b1d5-cbdfad45920e">

**Comment by flatsiedatsie** [comment]
Got a bit further. This model works fine on llama.cpp, but has some strange behaviour in wllama. But I'll try fiddling with some settings.

<img width="374" alt="Screenshot 2024-06-23 at 22 39 06" src="https://github.com/ngxson/wllama/assets/805405/cacaf19b-8455-452f-942d-f2cf67548c65">

**Comment by flatsiedatsie** [comment]
I've put a quick (still broken) demo here:
https://github.com/flatsiedatsie/bitnet_in_the_browser/

**Comment by felladrin** [comment]
Keep pushing it, @flatsiedatsie!

**Comment by ngxson** [comment]
Very cool @flatsiedatsie

Just my personal POV, maybe firstly we make sure that it runs absolutely stable on native llama.cpp, then we will see what's the problem when bringing it to wllama. That way we can narrow down the scope when searching for a bug.

> Got a bit further.[ This model](https://huggingface.co/BoscoTheDog/bitnet_b1_58-xl_q8_0_gguf/tree/main) works fine on llama.cpp, but has some strange behaviour in wllama. But I'll try fiddling with some settings.

The generation seems to work fine. I suspect maybe something to do with special tokens and chat template

**Comment by ngxson** [comment]
So, turns out the available model is not instruction-tuned, so we can't expect it to be usable for chat. See: https://huggingface.co/BoscoTheDog/bitnet_b1_58-xl_q8_0_gguf/blob/main/tokenizer_config.json

At this point, it seems to be working at inference level. Not much we can do to fix the chat issue (which requires training / fine tuning the model). I'll release a new version of wllama with up-to-date source code so we're ready when new models appear.

Also note that, mul_mat is not (yet) optimized for bitnet, so we can't expect good level of performance out of llama.cpp.

**Comment by flatsiedatsie** [comment]
Here's another specialized version of the model, straight from the horse's mouth:

https://huggingface.co/imi2/test/resolve/refs%2Fpr%2F10/bitnet_b1_58-3B-Q1_3-1.63bpw.gguf

via
https://www.reddit.com/r/LocalLLaMA/comments/1dnbf6s/33b_bitnet_test_on_1gb_ram_retro_handheld/ (worth a read)

I couldn't get that to run on my mac yesterday though, probably because up to an hour ago it wasn't optimized for ARM yet. Things move so fast..

> There's also the 700M BitNet model (named "large") which in Q1_3 takes only 171 MiB, which is useful if you're very low on RAM. And its speed is more usable on low-end devices (getting close to 7 tokens per seconds on 4 Arm cortex-a53 cores (phone), and 7.5 tok/s with 4 cortex-a72 cores (rpi4)).

**Comment by flatsiedatsie** [comment]
I found a bitnet model that, [in theory, is instruct tuned](https://www.oxen.ai/ox/BitNet/dir/main/models/bitnet_b1_58-large-instruct/final_checkpoint).

Running it results in the same gobbledygook though.

<img width="569" alt="Screenshot 2024-06-26 at 17 54 21" src="https://github.com/ngxson/wllama/assets/805405/fd02eb5f-4400-4758-a68b-f4df5808a053">

I'm uploading the Q16 .gguf version I made [here](https://huggingface.co/BoscoTheDog/bitnet_instruct_q16_gguf).

I also tested it with llama.cpp and it runs, although it seems to have a fascination with Cow emojis.

<img width="909" alt="Screenshot 2024-06-26 at 17 59 44" src="https://github.com/ngxson/wllama/assets/805405/5839eb87-5f1d-472a-b78d-240798ceddc2">


<img width="556" alt="Screenshot 2024-06-26 at 17 58 01" src="https://github.com/ngxson/wllama/assets/805405/0ceeeaad-e2d2-414e-ba07-8fc607005507">

This almost seemed like an answer at first:
<img width="569" alt="Screenshot 2024-06-26 at 18 07 30" src="https://github.com/ngxson/wllama/assets/805405/adfc6d93-1de0-460d-9377-41004766d512">

**Comment by flatsiedatsie** [comment]
Ah, this may explain the cow theme:

<img width="1610" alt="Screenshot 2024-06-26 at 18 19 57" src="https://github.com/ngxson/wllama/assets/805405/881ff9d8-8fe4-4395-b376-d6e8c6adcd84">

And the name "Bessie" Seems to be a good output for this model too.

**Comment by flatsiedatsie** [comment]
I must admit I still don't quite grasp why it doesn't work. 

I've kept trying with various models, but they all output.. repetitive strangeness. Often large amount of newlines.

Even if they are just base models, feeding them "Once upon a time" should result in something of a story, right? And since it does seem to work with the llama.cpp binary, what could be different about the wasm version?

**Comment by ngxson** [comment]
IMO the most simple way is to test if the same prompt works with original HF transformers python library. After all, someone uploads a model doesn't mean it will work.

**Comment by flatsiedatsie** [comment]
OMG I FIGURED IT OUT!

All I had to do was add `<s>` before the prompt!

<img width="563" alt="Screenshot 2024-07-07 at 20 31 11" src="https://github.com/ngxson/wllama/assets/805405/90dd24c2-bccc-4124-971c-3925ce01ff11">

**Comment by felladrin** [comment]
That's great news @flatsiedatsie!

Now we just need to find a good instruction-tuned one. Keep us posted! 🎉

**Comment by flatsiedatsie** [comment]
Thanks! Will do!

**Comment by flatsiedatsie** [comment]
This error could be my "work offline" modification, but I thought I'd share:

<img width="753" alt="Screenshot 2024-07-07 at 21 55 32" src="https://github.com/ngxson/wllama/assets/805405/8b1b57eb-942a-466f-bf4d-c1e580b31a60">

**Comment by mindplay-dk** [comment]
Looks like someone did it?

https://github.com/Nexesenex/ik_llama.cpp.nxs?tab=readme-ov-file

Seems there's a WASM build, but I can't find a browser demo... and the instruction-tuned BitNet is not available anyway? hm.

(I wanted to build a fully-local bookmark management chrome extension with [local embeddings and search](https://github.com/babycommando/entity-db), and BitNet would be great for generating summaries of pages you visit... but maybe I'm dreaming. 😌)

**Comment by flatsiedatsie** [comment]
Interesting.

I recently tried to build Wllama but substituting [Microsoft's fork of llama.cpp](https://github.com/microsoft/BitNet). It was a long shot, and it didn't work.

I did so because Microsoft has released an actual 2B Bitnet model that seems worth using:
https://www.reddit.com/r/LocalLLaMA/comments/1jzp5or/microsoft_has_released_a_fresh_2b_bitnet_model/

I've tried that model on a Raspberry Pi, and was impressed by what appeared to be low memory use:
https://www.reddit.com/r/LocalLLaMA/comments/1kbdi9l/raspberry_pi_5_a_small_comparison_between_qwen3/

Off topic:

There might also be a way to convert normal models to bitnet models now:
https://www.reddit.com/r/LocalLLaMA/comments/1klxlbx/bitnet_finetunes_of_r1_distills/

This also looks like a great further improvement of Bitnet:
https://www.reddit.com/r/LocalLLaMA/comments/1k9mjov/bitnet_v2_native_4bit_activations_with_hadamard/

summarized:

> In short, by switching to using 4-bit Activations with the same size model they can:
> 
> - Keep the same size on disk
> - Halve the size of the KV Cache, decreasing how much memory is used by the context
> - Use INT4 operations, potentially doubling the theoretical computational throughput

[source](https://jackson.dev/post/dont-sleep-on-bitnet/)
