### ISSUE TITLE
The mystery of Schrodinger's exit function

### ISSUE THREAD

**Issue by flatsiedatsie** [ngxson/wllama#82]
This is a mystery to me. In the code below I check that Wllama exists, and that `exit`is a function on the Wllama object.

Yet when I call it, I sometimes get this error:

<img width="564" alt="Screenshot 2024-07-03 at 12 20 33" src="https://github.com/ngxson/wllama/assets/805405/498901d7-a0a1-46a7-85ee-9accc5741e40">

```
if(window.llama_cpp_app != null && typeof window.llama_cpp_app.exit === 'function'){
			console.log("calling Wllama exit");
			try{
				await window.llama_cpp_app.exit();
			}
			catch(err){
				console.error("caught error trying to stop Wllama: ", err);
			}
			
		}
		else{
			console.warn(" window.llama.cpp was null, or window.llama_cpp_app.exit was undefined.  window.llama_cpp_app: ", window.llama_cpp_app);
		}
```

**Comment by ngxson** [comment]
You need to call `loadModel` before `exit`. Otherwise `this.proxy` is null:

https://github.com/ngxson/wllama/blob/d20441c36907938f60491ccd1fefc48186a2fb53/src/wllama.ts#L302

Additionally, we can add a optional chaining (?.) inside `exit` function to make sure we don't call proxy if it's null

```ts
  /**
   * Unload the model and free all memory
   */
  async exit(): Promise<void> {
    await this.proxy?.wllamaExit();
  }
```

**Comment by flatsiedatsie** [comment]
Ah, that must be it. Makes total sense. I had to start loading Wllama "empty" from the start because of the new caching system so I could get a list of already cached files from it when the page first loads. 

Would you like me to create a PR?
