### ISSUE TITLE
main: initialize main example

### ISSUE THREAD

**Issue by ngxson** [ngxson/wllama#96]
initialize "main" example with:
- vite + react-typescript
- tailwindcss + daisyui

functionalities:
- manage models in cache (download / list / delete)
- load model
- send message + manage multiple conversations
- edit sampling params

reference UI (built from off-the-shelf daisyui components)

![Image](https://github.com/user-attachments/assets/d92f01a1-580f-4bc6-93f2-89b9056b6780)

**Comment by felladrin** [comment]
The UI is amazing! Thanks for adding that!
The model loading feature is marvelous! It's the perfect playground to test models before deciding to use them!

**Comment by ngxson** [comment]
@felladrin Yup thanks! Feel free to report bugs if you see one
